version: "3.7"

services:
  eta2influx:
    image: eta_to_influx:latest
    environment:
      - INFLUX_HOST='influxdb'
      - ETA_URL=http://192.168.178.68:8080/user/var
      - time_delay_seconds=60
    stdin_open: true
    tty: true